# Generated by Django 3.1.3 on 2020-11-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kospi',
            name='code',
            field=models.CharField(max_length=255, verbose_name='코드'),
        ),
    ]
